name: symterra_rich_text_example
publish_to: 'none'
description: Example app for SymTerraRichTextController
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  symterra_rich_text_controller:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
